kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "dev"
    dry_run: true

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
